### ISSUE TITLE
Add a page for "Publications based on solids4foam"

### ISSUE THREAD

**Issue by philipcardiff** [solids4foam/solids4foam.github.io#50]
It would be useful to add a page to the website that lists publications (papers, conferences, websites, projects, etc.) based on or use solids4foam in some way.

This page could be placed in the "About" section (or maybe documentation). Here is a provisional list (a quick check via Scopus with the keyword "solids4foam" but I definitely missed some/many):
- Yu Hsiao, Shih-Chun Hsiao, Philip Li-Fan Liu, Two-dimensional numerical simulations of solitary wave interaction with a vertical elastic plate, Ocean Engineering, https://doi.org/10.1016/j.oceaneng.2023.115160.
- S.A. Brown, N. Xie, M.R. Hann, D.M. Greaves, Investigation of wave-driven hydroelastic interactions using numerical and physical modelling approaches,
Applied Ocean Research, https://doi.org/10.1016/j.apor.2022.103363.
[validation and verification] Attili, T., Heller, V., & Triantafyllou, S. (2021). A numerical investigation of tsunamis impacting dams. Coastal Engineering, 169, 103942. https://doi.org/10.1016/j.coastaleng.2021.103942.
- Attili, T., Heller, V., & Triantafyllou, S. (2023). Wave impact on rigid and flexible plates. Coastal Engineering, 182, 104302. https://doi.org/10.1016/j.coastaleng.2023.104302.
- Huang, L., Ren, K., Li, M., Tuković, Ž., Cardiff, P., & Thomas, G. (2019). Fluid-structure interaction of a large ice sheet in waves. Ocean Engineering, 182, 102-111. https://doi.org/10.1016/j.oceaneng.2019.04.015
- Attili, T., Heller, V., & Triantafyllou, S. (2023). Scaling approaches and scale effects in wave–flexible structure interaction. Journal of Fluids and Structures, 123, 103987. https://doi.org/10.1016/j.jfluidstructs.2023.103987.
- Salachna, J., Cioncolini, A., & Iacovides, H. (2023). Benchmark simulation of the flow-induced vibrations for nuclear applications. Annals of Nuclear Energy, 180, 109425. https://doi.org/10.1016/j.anucene.2022.109425.
- Michael Herty, Elisa Iacomini, Giuseppe Visconti, Recent Trends on Nonlinear Filtering for Inverse Problems, Commun. Appl. Ind. Math. 13 (1), 2022, 10–20, 10.2478/caim-2022-0002.
- Rodrigues, P. V., Ramoa, B., Machado, A. V., Cardiff, P., & Nóbrega, J. M. Assessing the Compressive and Impact Behavior of Plastic Safety Toe Caps through Computational Modelling. Polymers, 13(24), 4332. https://doi.org/10.3390/polym13244332
- Šekutkovski, B., Kostić, I., Simonović, A., Cardiff, P., & Jazarević, V. (2016). Three-dimensional fluid–structure interaction simulation with a hybrid RANS–LES turbulence model for applications in transonic flow domain. Aerospace Science and Technology, 49, 1-16. https://doi.org/10.1016/j.ast.2015.11.028
- Cardiff, P., Tuković, Ž., Jaeger, P. D., Clancy, M., & Ivanković, A. (2017). A Lagrangian cell-centred finite volume method for metal forming simulation. International Journal for Numerical Methods in Engineering, 109(13), 1777-1803. https://doi.org/10.1002/nme.5345
-  Tuković, Ž., Bukač, M., Cardiff, P., Jasak, H., Ivanković, A. (2019). Added Mass Partitioned Fluid–Structure Interaction Solver Based on a Robin Boundary Condition for Pressure. In: Nóbrega, J., Jasak, H. (eds) OpenFOAM® . Springer, Cham. https://doi.org/10.1007/978-3-319-60846-4_1
- Tuković, Ž., Jasak, H., Karač, A., Cardiff, P., Ivanković, A. Openfoam finite volume solver for fluid-solid interaction. Transactions of Famena, 2018, 42(3), pp. 1–31.
-  Tang, T., Hededal, O., & Cardiff, P. (2015). On finite volume method implementation of poro-elasto-plasticity soil model. International Journal for Numerical and Analytical Methods in Geomechanics, 39(13), 1410-1430. https://doi.org/10.1002/nag.2361
-  Cardiff, P., Karač, A., & Ivanković, A. (2014). A large strain finite volume method for orthotropic bodies with general material orientations. Computer Methods in Applied Mechanics and Engineering, 268, 318-335. https://doi.org/10.1016/j.cma.2013.09.008
-  Cardiff, P., Karač, A., & Ivanković, A. (2012). Development of a finite volume contact solver based on the penalty method. Computational Materials Science, 64, 283-284. https://doi.org/10.1016/j.commatsci.2012.03.011
-  Cardiff, P., Tuković, Ž., Jasak, H., & Ivanković, A. (2016). A block-coupled Finite Volume methodology for linear elasticity and unstructured meshes. Computers & Structures, 175, 100-122. https://doi.org/10.1016/j.compstruc.2016.07.004
-  Batistić, I., Cardiff, P., & Tuković, Ž. (2022). A finite volume penalty based segment-to-segment method for frictional contact problems. Applied Mathematical Modelling, 101, 673-693. https://doi.org/10.1016/j.apm.2021.09.009

We can give instructions explaining how people can add to this list via a pull request. I guess we should give the list in chronological order (or reverse chronological).

**Comment by iBatistic** [comment]
@philipcardiff do you want to group things into papers, conferences, book chapters, and projects or do you think to chunk everything into one list?

**Comment by cloner0110** [comment]
How about something like this https://precice.org/community-projects.html ?

But of course, with fewer details.

**Comment by philipcardiff** [comment]
> @iBatistic @philipcardiff How about something like this https://precice.org/community-projects.html ?
> 
> But of course, with fewer details.

The preCICE page looks nice.

> @philipcardiff do you want to group things into papers, conferences, book chapters, and projects or do you mean to group everything into one list?

To start with, I suggest we keep everything in one list (maybe it is a bit easier).

The preCICE page looks good; maybe, to begin with, a simple page with a list is fine. (I guess creating and maintaining a page is much more time-consuming than a list).We could then extend this later. But, of course, I am open to suggestions. Feel free to propose something.

**Comment by iBatistic** [comment]
@philipcardiff, @cloner0110 I made a PR(#51) for a bulleted list of publications; they are sorted by year and type.  I still need to go through the list to standardize the way of referencing, and to add what is missing.
 let me know what you think

**Comment by philipcardiff** [comment]
Resolved in https://github.com/solids4foam/solids4foam.github.io/pull/51

**Comment by philipcardiff** [comment]
> @philipcardiff, @cloner0110 I made a PR(#51) for a bulleted list of publications; they are sorted by year and type. I still need to go through the list to standardize the way of referencing, and to add what is missing.
> let me know what you think

This looks great, Ivan. I like the coloured bullet points.

I push a couple of minor edits. In particular, the instructions on how to add a new entry, where I think doing it all through the web browser is probably easiest for most people, rather than editing a local clone. We could keep both instructions if you think it is needed.

**Comment by iBatistic** [comment]
> The publications listed below are based on the solids4foam library and its predecessor, the Extend Bazaar FSI toolbox, and other solid mechanics codes from foam-extend.

I didn't even think of that! That's the best option :)

Thnx for the edits, now is rendered properly on the page.

**Comment by cloner0110** [comment]
Looks great @iBatistic , great job.
