### ISSUE TITLE
Openfoam overset mesh error

### ISSUE THREAD

**Issue by Aman7570** [solids4foam/solids4foam.github.io#58]
I am attempting to couple OpenFOAM with a dummy solver, referring to the solid4Foam cylinder overset mesh as a reference. Without the precice function in controlDict , it runs without errors. However, when I add the function and controlDict and preciceDict , it shows an error.

FOAM FATAL IO ERROR: (openfoam-2312)
inconsistent patch and patchField types for
patch type overset and patchField type zeroGradient

file: 0/zoneID/boundaryField/oversetPatch at line 28955.
https://github.com/Aman7570/precice/blob/main/cylinder_precice1-20240318T073823Z-001.zip

**Comment by philipcardiff** [comment]
Hi @Aman7570, it seems like your question would be better placed in the preCICE forum. If I understand correctly, you are trying to develop a new solid solver to couple with OpenFOAM via preCICE (which are not related to solids4foam)?

**Comment by Aman7570** [comment]
okk, Thanks you
